//
//  SamplesPictures.swift
//  Health Import
//
//  Created by Antonio Carranza López on 17/11/15.
//  Copyright © 2015 Antonio Carranza López. All rights reserved.
//

import Foundation

// Body Measurements
let SamplesPictures = ["HKQuantityTypeIdentifierBodyMassIndex":"BodyMeasurements",
"HKQuantityTypeIdentifierBodyFatPercentage":"BodyMeasurements",
"HKQuantityTypeIdentifierHeight":"BodyMeasurements",
"HKQuantityTypeIdentifierBodyMass":"BodyMeasurements",
"HKQuantityTypeIdentifierLeanBodyMass":"BodyMeasurements",
"HKQuantityTypeIdentifierStepCount":"Fitness",
"HKQuantityTypeIdentifierDistanceWalkingRunning":"Fitness",
"HKQuantityTypeIdentifierDistanceCycling":"Fitness",
"HKQuantityTypeIdentifierBasalEnergyBurned":"Fitness",
"HKQuantityTypeIdentifierActiveEnergyBurned":"Fitness",
"HKQuantityTypeIdentifierFlightsClimbed":"Fitness",
"HKQuantityTypeIdentifierNikeFuel":"Fitness",
"HKQuantityTypeIdentifierHeartRate":"Vitals",
"HKQuantityTypeIdentifierBodyTemperature":"Vitals",
"HKQuantityTypeIdentifierBasalBodyTemperature":"Vitals",
"HKQuantityTypeIdentifierBloodPressureSystolic":"Vitals",
"HKQuantityTypeIdentifierBloodPressureDiastolic":"Vitals",
"HKQuantityTypeIdentifierRespiratoryRate":"Vitals",
"HKQuantityTypeIdentifierOxygenSaturation":"Results",
"HKQuantityTypeIdentifierPeripheralPerfusionIndex":"Results",
"HKQuantityTypeIdentifierBloodGlucose":"Results",
"HKQuantityTypeIdentifierNumberOfTimesFallen":"Results",
"HKQuantityTypeIdentifierElectrodermalActivity":"Results",
"HKQuantityTypeIdentifierInhalerUsage":"Results",
"HKQuantityTypeIdentifierBloodAlcoholContent":"Results",
"HKQuantityTypeIdentifierForcedVitalCapacity":"Results",
"HKQuantityTypeIdentifierForcedExpiratoryVolume1":"Results",
"HKQuantityTypeIdentifierPeakExpiratoryFlowRate":"Results",
"HKQuantityTypeIdentifierDietaryBiotin":"Nutrition",
"HKQuantityTypeIdentifierDietaryCaffeine":"Nutrition",
"HKQuantityTypeIdentifierDietaryCalcium":"Nutrition",
"HKQuantityTypeIdentifierDietaryCarbohydrates":"Nutrition",
"HKQuantityTypeIdentifierDietaryChloride":"Nutrition",
"HKQuantityTypeIdentifierDietaryCholesterol":"Nutrition",
"HKQuantityTypeIdentifierDietaryChromium":"Nutrition",
"HKQuantityTypeIdentifierDietaryCopper":"Nutrition",
"HKQuantityTypeIdentifierDietaryEnergyConsumed":"Nutrition",
"HKQuantityTypeIdentifierDietaryFatMonounsaturated":"Nutrition",
"HKQuantityTypeIdentifierDietaryFatPolyunsaturated":"Nutrition",
"HKQuantityTypeIdentifierDietaryFatSaturated":"Nutrition",
"HKQuantityTypeIdentifierDietaryFatTotal":"Nutrition",
"HKQuantityTypeIdentifierDietaryFiber":"Nutrition",
"HKQuantityTypeIdentifierDietaryFolate":"Nutrition",
"HKQuantityTypeIdentifierDietaryIodine":"Nutrition",
"HKQuantityTypeIdentifierDietaryIron":"Nutrition",
"HKQuantityTypeIdentifierDietaryMagnesium":"Nutrition",
"HKQuantityTypeIdentifierDietaryManganese":"Nutrition",
"HKQuantityTypeIdentifierDietaryMolybdenum":"Nutrition",
"HKQuantityTypeIdentifierDietaryNiacin":"Nutrition",
"HKQuantityTypeIdentifierDietaryPantothenicAcid":"Nutrition",
"HKQuantityTypeIdentifierDietaryPhosphorus":"Nutrition",
"HKQuantityTypeIdentifierDietaryPotassium":"Nutrition",
"HKQuantityTypeIdentifierDietaryProtein":"Nutrition",
"HKQuantityTypeIdentifierDietaryRiboflavin":"Nutrition",
"HKQuantityTypeIdentifierDietarySelenium":"Nutrition",
"HKQuantityTypeIdentifierDietarySodium":"Nutrition",
"HKQuantityTypeIdentifierDietarySugar":"Nutrition",
"HKQuantityTypeIdentifierDietaryThiamin":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminA":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminB12":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminB6":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminC":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminD":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminE":"Nutrition",
"HKQuantityTypeIdentifierDietaryVitaminK":"Nutrition",
"HKQuantityTypeIdentifierDietaryWater":"Nutrition",
"HKQuantityTypeIdentifierDietaryZinc":"Nutrition",
"HKQuantityTypeIdentifierUVExposure":"Results",
"HKCategoryTypeIdentifierSleepAnalysis":"Sleep",
"HKCategoryTypeIdentifierAppleStandHour":"Sleep",
"HKCategoryTypeIdentifierCervicalMucusQuality":"ReproductiveHealth",
"HKCategoryTypeIdentifierOvulationTestResult":"ReproductiveHealth",
"HKCategoryTypeIdentifierMenstrualFlow":"ReproductiveHealth",
"HKCategoryTypeIdentifierIntermenstrualBleeding":"ReproductiveHealth",
"HKCategoryTypeIdentifierSexualActivity":"ReproductiveHealth",
"HKCharacteristicTypeIdentifierBiologicalSex":"ReproductiveHealth",
"HKCharacteristicTypeIdentifierBloodType":"Me",
"HKCharacteristicTypeIdentifierDateOfBirth":"Me",
"HKCharacteristicTypeIdentifierFitzpatrickSkinType":"Me",
"HKCorrelationTypeIdentifierBloodPressure":"Vitals",
"HKCorrelationTypeIdentifierFood":"Me",
"HKWorkoutTypeIdentifier":"Fitness"]
